//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CV_MVCEntities : DbContext
    {
        public CV_MVCEntities()
            : base("name=CV_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CV_STUDENT> CV_STUDENT { get; set; }
        public virtual DbSet<FACULTIES> FACULTIES { get; set; }
        public virtual DbSet<SCHOOL> SCHOOL { get; set; }
        public virtual DbSet<SKILL> SKILL { get; set; }
        public virtual DbSet<STATUS> STATUS { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<STUDENT_EXPERIENCE> STUDENT_EXPERIENCE { get; set; }
        public virtual DbSet<STUDENT_SKILL> STUDENT_SKILL { get; set; }
    }
}
