//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SCHOOL
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public int STATUS_FK { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public Nullable<int> ALTER_USER { get; set; }
        public System.DateTime ALTER_DATE { get; set; }
        public string CODE { get; set; }
        public string HOUR_ABSENT { get; set; }
        public Nullable<int> DAY_ABSENT { get; set; }
        public Nullable<int> TYPEOFTRAINING_FK { get; set; }
    }
}
