//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class STUDENT_EXPERIENCE
    {
        public int ID { get; set; }
        public Nullable<int> STUDENT_FK { get; set; }
        [Required(ErrorMessage = "Không được để trống")]
        public string COMPANY_NAME { get; set; }
        [Required(ErrorMessage = "Không được để trống")]    
        public string TITLE { get; set; }
        public Nullable<int> FROM_MONTH { get; set; }
        public Nullable<int> TO_MONTH { get; set; }
        public Nullable<int> FROM_YEAR { get; set; }
        public Nullable<int> TO_YEAR { get; set; }
        public string DESCRIPTION_JOB { get; set; }
        public Nullable<double> SALARY { get; set; }
    }
}
